version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: fintrack-pgsql
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_ROOT_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=fintrack'
    volumes:
      - ./fintrackdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  fintrack:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fintrack-backend
    ports:
      - '8080:8080'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgresql:5432/fintrack'
      - 'DATABASE_USERNAME=postgres'
      - 'DATABASE_PASSWORD=postgres'
    depends_on:
      - postgresql