CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_to_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_to_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE users_to_roles
    ADD CONSTRAINT fk_usetorol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE users_to_roles
    ADD CONSTRAINT fk_usetorol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO roles (name)
VALUES ('ROLE_USER');
INSERT INTO roles (name)
VALUES ('ROLE_MODERATOR');
INSERT INTO roles (name)
VALUES ('ROLE_ADMIN');